apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: p8ty0ww2w-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-db38a92f04.2jb9.p3.openshiftapps.com/rhtap/rhtap-qe:4e526d25af2aab74aa80f5086f80eb4247ec61e1@sha256:c269159734be3f2ba8daeb09e4eef21df37ea552c61fd2317e7e79f2159d29fd
          name: container-image
